# Generated by Django 4.1.3 on 2023-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("potw_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="closing_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="open_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="ratings",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="socials",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
