openapi: 3.0.3
info:
  title: Party on the weekend
  version: 1.0.0
  description: Have fun partying!
paths:
  /potw/api:
    get:
      operationId: potw_api_retrieve
      tags:
      - potw
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
